apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-service.fullname" . }}-config
  labels:
    {{- include "tenant-service.labels" . | nindent 4 }}
data:
  service_account_email: {{ .Values.gcp.serviceAccountEmail | quote }}
  project_id: {{ .Values.gcp.projectId | quote }}
  backend_url: {{ .Values.backendUrl | quote }}
  identity_platform_auth_enabled: {{ .Values.identityPlatform.authEnabled | quote }}
  identity_platform_auth_primary_header: {{ .Values.identityPlatform.primaryHeader | quote }}
  identity_platform_auth_fallback_header: {{ .Values.identityPlatform.fallbackHeader | quote }}
  {{- if .Values.mongodb.enabled }}
  mongodb_connection_string: {{ .Values.mongodb.connectionString | quote }}
  mongodb_database: {{ .Values.mongodb.database | quote }}
  {{- end }}

