apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - configmap.yaml
  - ingress.yaml
  - itinerary-deployment.yaml
  - itinerary-service.yaml
  - service-account.yaml