apiVersion: v1
    app: recommendation-service
  labels:
    iam.gke.io/gcp-service-account: "travel-backend-sa@graphite-plane-474510-s9.iam.gserviceaccount.com"
  annotations:
  name: recommendation-service-sa
metadata:
kind: ServiceAccount

