apiVersion: v2
name: itinerary-service
description: A Helm chart for the Itinerary Service - Travel Planning Application
type: application
version: 1.0.0
appVersion: "2.2.10"
keywords:
  - itinerary
  - travel
  - quarkus
maintainers:
  - name: CAD Team
    email: benedikt.scheffel@gmail.com

