apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-warnings-config
data:
  SMTP_FROM: "noreply.travel-warning@htwg-konstanz.de"
  SMTP_HOST: "smtp.htwg-konstanz.de"
  SMTP_PORT: "587"
  SMTP_START_TLS: "REQUIRED"
  DB_URL: "jdbc:postgresql://warnings-postgres:5432/travel_warnings_db"
