apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: warnings-tls-cert
  namespace: default
spec:
  secretName: warnings-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - warnings.tripico.fun