apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-warnings-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: tripico.fun
      http:
        paths:
          - path: /travel-warnings-service/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: travel-warnings-api
                port:
                  number: 8080
