apiVersion: apps/v1
kind: Deployment
metadata:
  name: warnings-postgres
spec:
  selector:
    matchLabels:
      app: warnings-postgres
  template:
    metadata:
      labels:
        app: warnings-postgres
    spec:
      containers:
        - name: warnings-postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: travel_warnings_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: warnings-postgres-storage
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d travel_warnings_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: warnings-postgres-storage
          persistentVolumeClaim:
            claimName: warnings-postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: warnings-postgres
spec:
  type: ClusterIP
  selector:
    app: warnings-postgres
  ports:
    - name: warnings-postgres
      port: 5432
      targetPort: 5432
