apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-warnings-api
spec:
  selector:
    matchLabels:
      app: travel-warnings-api
  template:
    metadata:
      labels:
        app: travel-warnings-api
    spec:
      containers:
        - name: travel-warnings-api
          image: ghcr.io/leotschritter/cad-backend-travel-warnings:8a81ec812761918b1b60df4aac6cf47217e58a72
          imagePullPolicy: Always
          env:
            - name: SMTP_FROM
              valueFrom:
                configMapKeyRef:
                  name: travel-warnings-config
                  key: SMTP_FROM
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: travel-warnings-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: travel-warnings-config
                  key: SMTP_PORT
            - name: SMTP_START_TLS
              valueFrom:
                configMapKeyRef:
                  name: travel-warnings-config
                  key: SMTP_START_TLS
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: travel-warnings-config
                  key: DB_URL

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PASSWORD

            # likely needed:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: travel_warnings_db
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres

          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: travel-warnings-api
spec:
  type: LoadBalancer
  selector:
    app: travel-warnings-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
