apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "itinerary-service.fullname" . }}-postgres-pvc
  labels:
    app: {{ include "itinerary-service.fullname" . }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresPvc.storage }}
