apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itinerary-service.fullname" . }}-db-secret
  labels:
    {{- include "itinerary-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  # Password must be provided via --set database.password=<password>
  password: ""
  {{- end }}

