{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "itinerary-service.serviceAccountName" . }}
  labels:
    {{- include "itinerary-service.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccountEmail }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

