apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weather-tls-cert
  namespace: default
spec:
  secretName: weather-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - weather.tripico.fun