apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: itinerary-tls-cert
  namespace: default
spec:
  secretName: itinerary-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - itinerary.tripico.fun