apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: recommendation-tls-cert
  namespace: default
spec:
  secretName: recommendation-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - recommendation.tripico.fun
