apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - neo4j-deployment.yaml
  - neo4j-pvc.yaml
  - neo4j-service.yaml
  - service.yaml
  - service-account.yaml

