apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  labels:
    app: neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7687
      targetPort: 7687
      protocol: TCP
      name: bolt
    - port: 7474
      targetPort: 7474
      protocol: TCP
      name: http
  selector:
    app: neo4j

