apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendation-service-sa
  annotations:
    iam.gke.io/gcp-service-account: "travel-backend-sa@graphite-plane-474510-s9.iam.gserviceaccount.com"
  labels:
    app: recommendation-service

