{{- if and .Values.ingress.enabled (not .Values.ingress.useProd) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.dev.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.recommendationApi.name }}
                port:
                  number: {{ .Values.recommendationApi.port }}
{{- end }}

